require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ChatRoomsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ChatRoom. As you add validations to ChatRoom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChatRoomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all chat_rooms as @chat_rooms" do
      chat_room = ChatRoom.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:chat_rooms)).to eq([chat_room])
    end
  end

  describe "GET show" do
    it "assigns the requested chat_room as @chat_room" do
      chat_room = ChatRoom.create! valid_attributes
      get :show, {:id => chat_room.to_param}, valid_session
      expect(assigns(:chat_room)).to eq(chat_room)
    end
  end

  describe "GET new" do
    it "assigns a new chat_room as @chat_room" do
      get :new, {}, valid_session
      expect(assigns(:chat_room)).to be_a_new(ChatRoom)
    end
  end

  describe "GET edit" do
    it "assigns the requested chat_room as @chat_room" do
      chat_room = ChatRoom.create! valid_attributes
      get :edit, {:id => chat_room.to_param}, valid_session
      expect(assigns(:chat_room)).to eq(chat_room)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChatRoom" do
        expect {
          post :create, {:chat_room => valid_attributes}, valid_session
        }.to change(ChatRoom, :count).by(1)
      end

      it "assigns a newly created chat_room as @chat_room" do
        post :create, {:chat_room => valid_attributes}, valid_session
        expect(assigns(:chat_room)).to be_a(ChatRoom)
        expect(assigns(:chat_room)).to be_persisted
      end

      it "redirects to the created chat_room" do
        post :create, {:chat_room => valid_attributes}, valid_session
        expect(response).to redirect_to(ChatRoom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chat_room as @chat_room" do
        post :create, {:chat_room => invalid_attributes}, valid_session
        expect(assigns(:chat_room)).to be_a_new(ChatRoom)
      end

      it "re-renders the 'new' template" do
        post :create, {:chat_room => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chat_room" do
        chat_room = ChatRoom.create! valid_attributes
        put :update, {:id => chat_room.to_param, :chat_room => new_attributes}, valid_session
        chat_room.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested chat_room as @chat_room" do
        chat_room = ChatRoom.create! valid_attributes
        put :update, {:id => chat_room.to_param, :chat_room => valid_attributes}, valid_session
        expect(assigns(:chat_room)).to eq(chat_room)
      end

      it "redirects to the chat_room" do
        chat_room = ChatRoom.create! valid_attributes
        put :update, {:id => chat_room.to_param, :chat_room => valid_attributes}, valid_session
        expect(response).to redirect_to(chat_room)
      end
    end

    describe "with invalid params" do
      it "assigns the chat_room as @chat_room" do
        chat_room = ChatRoom.create! valid_attributes
        put :update, {:id => chat_room.to_param, :chat_room => invalid_attributes}, valid_session
        expect(assigns(:chat_room)).to eq(chat_room)
      end

      it "re-renders the 'edit' template" do
        chat_room = ChatRoom.create! valid_attributes
        put :update, {:id => chat_room.to_param, :chat_room => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chat_room" do
      chat_room = ChatRoom.create! valid_attributes
      expect {
        delete :destroy, {:id => chat_room.to_param}, valid_session
      }.to change(ChatRoom, :count).by(-1)
    end

    it "redirects to the chat_rooms list" do
      chat_room = ChatRoom.create! valid_attributes
      delete :destroy, {:id => chat_room.to_param}, valid_session
      expect(response).to redirect_to(chat_rooms_url)
    end
  end

end
